#!/sbin/openrc-run

# Sample init.d file for alpine linux.

name=ocat
command="/usr/bin/$name"
command_args="-P /run/ocat.pid $onion_address"
command_background="yes"

start_stop_daemon_args=""
pidfile="/run/$name.pid"

depend() {
	need net
	after firewall
}

checkconfig() {
	if [ -z "$onion_address" ]
	then
		eerror '$onion_address must be specified. See https://www.onioncat.org/configuration/ for more information.'
		return 1
	fi
}

start_pre() {
	checkconfig || return 1
}
