.Dd December 12, 2017
.Dt QUICKSERV 1 PRM


.Sh NAME
.Nm quickserv
.Nd quickly and dirtily serve a folder as a HTTP server.


.Sh SYNOPSIS
.Nm
.Op Fl dir Ar DIRECTORY
.Op Fl port Ar PORT


.Sh DESCRIPTION
.Nm
serves a local directory of files as an HTTP server.

.Bl -tag -width "pkgname-pkgver" -offset indent -compact

.It Fl dir Ar DIRECTORY
Specifies the local path to be served over HTTP.

.It Fl port Ar PORT
Specifies the TCP port that quickserv will bind to.

.El


.Sh EXAMPLES

quickserv

quickserv -dir ~/public_html -port 9001


.Sh SEE ALSO

https://godoc.org/net/http#Dir


.Sh AUTHORS

.Nm :
.An Christine Dodrill Aq me@christine.website
